INSERT INTO mechanics(id,name) VALUES ('n1GtBt35Rd','Acting');
INSERT INTO mechanics(id,name) VALUES ('PGjmKGi26h','Action / Movement Programming');
INSERT INTO mechanics(id,name) VALUES ('oeg6wN9Eoc','Action Point Allowance System');
INSERT INTO mechanics(id,name) VALUES ('ckCp1oTVMy','Action Queue');
INSERT INTO mechanics(id,name) VALUES ('Bc7R8pLoGk','Action Selection');
INSERT INTO mechanics(id,name) VALUES ('05zCZoLvQJ','Area Control');
INSERT INTO mechanics(id,name) VALUES ('3te2oybNR4','Area Enclosure');
INSERT INTO mechanics(id,name) VALUES ('9NBcz45nN7','Area Majority/ Influence');
INSERT INTO mechanics(id,name) VALUES ('bgGxE0pI2B','Area Movement');
INSERT INTO mechanics(id,name) VALUES ('amcImLdOmD','Asymmetric');
INSERT INTO mechanics(id,name) VALUES ('AZxlPpi5oq','Auction');
INSERT INTO mechanics(id,name) VALUES ('3tuJiW3pps','Betting');
INSERT INTO mechanics(id,name) VALUES ('ZX3hYcF9H7','Bluffing');
INSERT INTO mechanics(id,name) VALUES ('UEzHyBWtz8','Building');
INSERT INTO mechanics(id,name) VALUES ('xuphiSlrxI','Campaign');
INSERT INTO mechanics(id,name) VALUES ('iWODHwRGuU','Card Drafting');
INSERT INTO mechanics(id,name) VALUES ('ebJKldFVeS','Card Game');
INSERT INTO mechanics(id,name) VALUES ('ngCSHHk0H2','Card Placement');
INSERT INTO mechanics(id,name) VALUES ('Gan96fffLL','Chit-Pull System');
INSERT INTO mechanics(id,name) VALUES ('0ez69aUfuJ','Communication Limits');
INSERT INTO mechanics(id,name) VALUES ('K0ykGhTMa8','Comodity Speculation');
INSERT INTO mechanics(id,name) VALUES ('AAi6B8NLaV','Confusion');
INSERT INTO mechanics(id,name) VALUES ('hwyCo1W0hi','Conversation');
INSERT INTO mechanics(id,name) VALUES ('33UT4gTFqy','Cooperative');
INSERT INTO mechanics(id,name) VALUES ('9mNukNBxfZ','Cooperative Play');
INSERT INTO mechanics(id,name) VALUES ('xVDf5dmJts','Crayon Rail System');
INSERT INTO mechanics(id,name) VALUES ('9y0yU5xWRU','Currency');
INSERT INTO mechanics(id,name) VALUES ('kZf6CVjtq7','D6 RPG');
INSERT INTO mechanics(id,name) VALUES ('vZsDDAdOoe','Deck Building');
INSERT INTO mechanics(id,name) VALUES ('GIdT5JqifB','Deck-Building');
INSERT INTO mechanics(id,name) VALUES ('GsNGxZFNCK','Deduction');
INSERT INTO mechanics(id,name) VALUES ('5kvyChnWuO','Dexterity');
INSERT INTO mechanics(id,name) VALUES ('lVSHu9efHv','Dice Building');
INSERT INTO mechanics(id,name) VALUES ('zw4KMn5rcD','Dice Movement');
INSERT INTO mechanics(id,name) VALUES ('R0bGq4cAl4','Dice Rolling');
INSERT INTO mechanics(id,name) VALUES ('wV5peB05xs','Drafting');
INSERT INTO mechanics(id,name) VALUES ('KfTS5BwIsu','Drawing');
INSERT INTO mechanics(id,name) VALUES ('Ouo00D4ka7','Drinking');
INSERT INTO mechanics(id,name) VALUES ('yu3eas6v7A','Engine Building');
INSERT INTO mechanics(id,name) VALUES ('hUn7uJHrYm','Euro Game');
INSERT INTO mechanics(id,name) VALUES ('kS8npG0jl8','Fighting');
INSERT INTO mechanics(id,name) VALUES ('S0O9ucexPS','Flicking');
INSERT INTO mechanics(id,name) VALUES ('qu5BcGjAzk','Grid Movement');
INSERT INTO mechanics(id,name) VALUES ('WPytek5P8l','Hand Management');
INSERT INTO mechanics(id,name) VALUES ('i3xnwJ7VPV','Hand-Eye Coordination');
INSERT INTO mechanics(id,name) VALUES ('6CyVyXRn1C','Hex and Counter');
INSERT INTO mechanics(id,name) VALUES ('BeD8NYAaSU','Hexagon Grid');
INSERT INTO mechanics(id,name) VALUES ('aQZ40lKv8O','Hidden Movement');
INSERT INTO mechanics(id,name) VALUES ('Voqy2dgrIM','Hidden Traitor');
INSERT INTO mechanics(id,name) VALUES ('DwmsVEvNVd','Legacy');
INSERT INTO mechanics(id,name) VALUES ('MaXzmoZUoX','Line Drawing');
INSERT INTO mechanics(id,name) VALUES ('UaLql58fua','Live action and Role Playing game (Larp)');
INSERT INTO mechanics(id,name) VALUES ('ar56ACXDNe','Mancala');
INSERT INTO mechanics(id,name) VALUES ('r6yIFvyXDD','Memory');
INSERT INTO mechanics(id,name) VALUES ('U3zhCQH7Et','Modular Board');
INSERT INTO mechanics(id,name) VALUES ('qxXud0DODh','Once per game ability');
INSERT INTO mechanics(id,name) VALUES ('UHdPUeuqyZ','Paper and Pencil');
INSERT INTO mechanics(id,name) VALUES ('GNtouC8NLm','Partnerships');
INSERT INTO mechanics(id,name) VALUES ('3dFd0RwsY4','Party Game');
INSERT INTO mechanics(id,name) VALUES ('9YdRn9J9oZ','Pattern Building');
INSERT INTO mechanics(id,name) VALUES ('uZJS07nXF5','Pattern Recognition');
INSERT INTO mechanics(id,name) VALUES ('BbTMRkwL0b','Pick-up and Deliver');
INSERT INTO mechanics(id,name) VALUES ('BGrhzIN69D','Player Elimination');
INSERT INTO mechanics(id,name) VALUES ('YyBg5CzHBF','Player vs. Player');
INSERT INTO mechanics(id,name) VALUES ('MEAoOygZsA','Point to Point Movement');
INSERT INTO mechanics(id,name) VALUES ('ea1eaPBQn8','Pool Building');
INSERT INTO mechanics(id,name) VALUES ('hmipYN1R1I','Press Your Luck');
INSERT INTO mechanics(id,name) VALUES ('24FWssBC3o','Puzzle');
INSERT INTO mechanics(id,name) VALUES ('E9VKQ8uMSP','Real Time');
INSERT INTO mechanics(id,name) VALUES ('Rt6V388y6M','Resource Gathering');
INSERT INTO mechanics(id,name) VALUES ('j7x8jY4ay2','Rock-Paper-Scissors');
INSERT INTO mechanics(id,name) VALUES ('EVeAdboGUA','Role Playing');
INSERT INTO mechanics(id,name) VALUES ('gRlslORtpI','Role Selection');
INSERT INTO mechanics(id,name) VALUES ('mGBzR68m8Z','Roll / Spin and Move');
INSERT INTO mechanics(id,name) VALUES ('zIPRS41oiN','Roll and Write');
INSERT INTO mechanics(id,name) VALUES ('FA6HjbhdNW','Rondel');
INSERT INTO mechanics(id,name) VALUES ('asw8k7EIJI','Route Building');
INSERT INTO mechanics(id,name) VALUES ('c6gkRM7rSy','Route/Network Building');
INSERT INTO mechanics(id,name) VALUES ('RwgEONzIzc','Secret Unit Deployment');
INSERT INTO mechanics(id,name) VALUES ('lA3KUtVFCy','Set Collection');
INSERT INTO mechanics(id,name) VALUES ('eRe1jJCBFe','Simulation');
INSERT INTO mechanics(id,name) VALUES ('DEvPj5twid','Simultaneous Play');
INSERT INTO mechanics(id,name) VALUES ('za4PP1LH00','Simultaneous action selection');
INSERT INTO mechanics(id,name) VALUES ('kuRNhFADjS','Skirmish');
INSERT INTO mechanics(id,name) VALUES ('x3wVCq1HEP','Social Deduction');
INSERT INTO mechanics(id,name) VALUES ('jbLrZb1xIb','Stock Holding');
INSERT INTO mechanics(id,name) VALUES ('GUoWg3Mfh5','Storytelling');
INSERT INTO mechanics(id,name) VALUES ('yDlgk7rXno','Tactical Movement');
INSERT INTO mechanics(id,name) VALUES ('jCRze30VP1','Tactics');
INSERT INTO mechanics(id,name) VALUES ('T8JEFYwoqy','Take That');
INSERT INTO mechanics(id,name) VALUES ('9jnCsVuRat','Teams');
INSERT INTO mechanics(id,name) VALUES ('8PN2HE86wg','Tile Placement');
INSERT INTO mechanics(id,name) VALUES ('cXd5KaXXZo','Time Track');
INSERT INTO mechanics(id,name) VALUES ('wEBvff5T5c','Tower Defense');
INSERT INTO mechanics(id,name) VALUES ('AVY6EvSQTP','Trading');
INSERT INTO mechanics(id,name) VALUES ('Vk7AWucmoL','Traitor');
INSERT INTO mechanics(id,name) VALUES ('tyTj0kxoRc','Traitor');
INSERT INTO mechanics(id,name) VALUES ('3GSQl800lk','Trick-taking');
INSERT INTO mechanics(id,name) VALUES ('zzsE4jtI1b','Variable Phase Order');
INSERT INTO mechanics(id,name) VALUES ('XM2FYZmBHH','Variable Player Powers');
INSERT INTO mechanics(id,name) VALUES ('JYYdBW6UCE','Voting');
INSERT INTO mechanics(id,name) VALUES ('yomuPpKFx4','Wargame');
INSERT INTO mechanics(id,name) VALUES ('fBOTEBUAmV','Worker Placement');
